
import { ImageResponse } from 'next/og';
import { fetchReportById } from '@/lib/report_utils';

export const runtime = 'nodejs';

export default async function Image({ params }: { params: { id: string } }) {
  const { id } = await params;
  const report = await fetchReportById(id);

  if (!report) {
    return new ImageResponse(
      (
        <div
          style={{
            fontSize: 48,
            background: '#0f1115',
            width: '100%',
            height: '100%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: 'white',
          }}
        >
          Report Not Found
        </div>
      ),
      { width: 1200, height: 630 }
    );
  }

  // Calculate Score
  const dimensionScores: number[] = [];
  Object.keys(report.scores).forEach(k => {
    if (k !== 'FINAL') dimensionScores.push(report.scores[k]);
  });
  const avgScore = dimensionScores.length > 0
    ? Math.round(dimensionScores.reduce((a, b) => a + b, 0) / dimensionScores.length * 10) / 10
    : 0;

  return new ImageResponse(
    (
      <div
        style={{
          background: 'linear-gradient(to bottom right, #0f1115, #1a1d24)',
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '40px',
          color: 'white',
          fontFamily: 'sans-serif',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', marginBottom: 20 }}>
          <div style={{ fontSize: 24, color: '#f59e0b', textTransform: 'uppercase', letterSpacing: 4 }}>
            IRSC Analyst Report
          </div>
        </div>

        <div style={{
          fontSize: 80,
          fontWeight: 'bold',
          background: 'linear-gradient(to right, #fef3c7, #f59e0b)',
          backgroundClip: 'text',
          color: 'transparent',
          marginBottom: 20,
          textAlign: 'center',
          lineHeight: 1.1
        }}>
          {report.companyName}
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: 40, marginTop: 40 }}>
          {/* Score Circle */}
          <div style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            width: 200,
            height: 200,
            borderRadius: '50%',
            border: '4px solid #f59e0b',
            background: 'rgba(245, 158, 11, 0.1)'
          }}>
            <div style={{ fontSize: 64, fontWeight: 'bold', color: 'white' }}>{avgScore}</div>
            <div style={{ fontSize: 16, color: '#94a3b8', marginTop: 4 }}>OVERALL</div>
          </div>

          {/* Stats */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            <div style={{ display: 'flex', fontSize: 24, color: '#e2e8f0' }}>
              Dimensions Evaluated: <span style={{ fontWeight: 'bold', marginLeft: 10, color: '#f59e0b' }}>8</span>
            </div>
            <div style={{ display: 'flex', fontSize: 24, color: '#e2e8f0' }}>
              Indicators Checked: <span style={{ fontWeight: 'bold', marginLeft: 10, color: '#f59e0b' }}>~400</span>
            </div>
            <div style={{ display: 'flex', fontSize: 24, color: '#e2e8f0' }}>
              Date: <span style={{ fontWeight: 'bold', marginLeft: 10, color: '#f59e0b' }}>{new Date().toLocaleDateString()}</span>
            </div>
          </div>
        </div>

        <div style={{ position: 'absolute', bottom: 40, fontSize: 16, color: '#64748b' }}>
          Generated by AI • Investment Due Diligence Tool
        </div>
      </div>
    ),
    {
      width: 1200,
      height: 630,
    }
  );
}
